version: "3"
services:
  db:
    image: postgres
  django:
    build:
      context: .
      dockerfile: images/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery:
    build:
      context: .
      dockerfile: images/django/Dockerfile
    command: celery -A scrapr worker -l info -B
    depends_on:
      - db
      - broker
    volumes:
      - .:/code
  broker:
    image: rabbitmq:3.7.8
    environment:
      - RABBITMQ_DEFAULT_VHOST=celery
