# Generated by Django 2.1.3 on 2018-11-12 16:46

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', djmoney.models.fields.CurrencyField(default='XYZ', max_length=3)),
                ('target_currency', djmoney.models.fields.CurrencyField(default='XYZ', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
    ]
